name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for git describe to work correctly

    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable # Or your preferred channel

    - name: Build Release Binaries (via Make)
      run: make build-release

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/torrs-linux-amd64
          dist/torrs-linux-arm64
          dist/torrs-darwin-amd64
          dist/torrs-darwin-arm64
          dist/torrs-windows-amd64.exe
          dist/torrs-windows-arm64.exe
        generate_release_notes: true
